### ISSUE TITLE
Add Validation to Prevent Overlapping Runtime

### ISSUE THREAD

**Issue by chengjieyao** [sgl-project/ome#30]
**Description**
Currently, when adding a new runtime (e.g. ClusterServingRuntime), there is no validation to ensure that its selection criteria (framework version, format, architecture, and size range) do not overlap with those of existing runtimes. Overlapping criteria can result in a model matching multiple runtimes, leading to ambiguous or incorrect runtime selection and potentially causing container startup failures or other errors.

**Why is this important?**
- Prevents ambiguous runtime matches, ensuring the correct container and configuration are always used.
- Improves reliability of model deployment and inference workflows.
- Reduces debugging time and risk of production incidents resulting from incompatible runtime selection and then failure of starting inference service.

**Example**
Suppose we have two runtime entries:
```
- modelFramework:
    name: transformers
    version: 4.45.0
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelArchitecture: LlamaForCausalLM
  modelSizeRange:
    min: 2B
    max: 4B

- modelFramework:
    name: transformers
    version:  4.45.0
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelArchitecture: LlamaForCausalLM
  modelSizeRange:
    min: 3B
    max: 5B
```
A model with Framework transformers version 4.45.0, architecture LlamaForCausalLM, format safetensors, and size 4B would match both runtimes, causing ambiguity. This is usually caused by incorrect runtime configuration. 

**Proposed Solution**
- Implement validation logic executed whenever a new runtime is added or updated.
- The validation should check for overlapping selection criteria between the new runtime and all existing ones.
- Integrate the validation into the make step and the Docker build process. If an overlap is detected, the make step or Docker build should fail and display a clear error message indicating the conflict, ensuring overlaps are resolved before proceeding.

**Acceptance Criteria**
-  Adding or updating a runtime that creates overlap with existing configurations should be prevented with a clear error.
-  An error message should clearly identify the conflicting existing runtime(s) and the specific fields that overlap.
